[Exception]
Ext=tpt
Ext=ini
Ext=bik
Ext=raw
Ext=umd
Ext=uax
Ext=sp2
Ext=u
Ext=xsr
Ext=tga

Ext=int
Ext=fra
Ext=deu
Ext=ita
Ext=esp
Ext=jap
Ext=kor
Ext=por

File=But_L_LOC.dds
File=But_L_LOC_deu.dds
File=But_L_LOC_esp.dds
File=But_L_LOC_fra.dds
File=But_L_LOC_int.dds
File=But_L_LOC_ita.dds
File=But_R_LOC.dds
File=But_R_LOC_deu.dds
File=But_R_LOC_esp.dds
File=But_R_LOC_fra.dds
File=But_R_LOC_int.dds
File=But_R_LOC_ita.dds

[Copy]
; mode = 0 (default): files are copied during init, before anything else
; mode = 1          : files are copied after mainmenu loaded, before mainmenu displayed (during the ubi/redstorm logo video or ESRB notice, which are not stoppable during this copy)
; mode = 2          : files are copied during mainmenu, started just after mode 1 finish (background), they are garanteed to be copied before loading the first map

File=(Src="Sounds\dsstdfx.bin")
File=(Src="Videos\P_Main\BG_MainMenu.bik")

File=(Src="MAGMA\DATA\TEXTURES\BG\PANEL\BUT_R_LOC_???.DDS")
File=(Src="MAGMA\DATA\TEXTURES\BG\PANEL\BUT_L_LOC_???.DDS")

File=(Src="System\xboxufiles.umd",mode=1)

File=(Src="Maps\Training_Team.xbx",mode=1)

File=(Src="Sounds\HD_Music.SS2",mode=1)
File=(Src="Sounds\???\HD_Music.LS2",mode=1)

File=(Src="Sounds\HD_Stream.SS2",mode=2)
File=(Src="Sounds\???\HD_Stream.LS2",mode=2)

File=(Src="Animations\R61stAssault_UKX.ukx",mode=2)
File=(Src="Animations\R61stGrenade_UKX.ukx",mode=2)
File=(Src="Animations\R61stHands_UKX.ukx",mode=2)
File=(Src="Animations\R61stItems_UKX.ukx",mode=2)
File=(Src="Animations\R61stLMG_UKX.ukx",mode=2)
File=(Src="Animations\R61stPistol_UKX.ukx",mode=2)
File=(Src="Animations\R61stShotgun_UKX.ukx",mode=2)
File=(Src="Animations\R61stSniper_UKX.ukx",mode=2)
File=(Src="Animations\R61stSub_UKX.ukx",mode=2)

File=(Src="StaticMeshes\R61stWeapons_SM.usx",mode=2)
File=(Src="StaticMeshes\R63rdWeapons_SM.usx",mode=2)
File=(Src="StaticMeshes\R6SFX_SM.usx",mode=2)

File=(Src="Textures\Inventory_t.utx",mode=2)
File=(Src="Textures\R61stWeapons_T.utx",mode=2)
File=(Src="Textures\R63rdWeapons_T.utx",mode=2)
File=(Src="Textures\R6SFX_T.utx",mode=2)
